# This file was generated by GoReleaser. DO NOT EDIT.
class DockerBrennen < Formula
  desc "Cleanup unused Docker resources."
  homepage "https://github.com/splo/docker-brennen/"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/splo/docker-brennen/releases/download/v0.2.0/docker-brennen_0.2.0_darwin_amd64.tar.gz"
    sha256 "414c933fa30e322bb701aec7ba797e18c78c0813279e9a581813c89086c05723"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/splo/docker-brennen/releases/download/v0.2.0/docker-brennen_0.2.0_linux_amd64.tar.gz"
      sha256 "0850511086353a4b9fc17d86696efffe45ab2ca3701d9e96ffaaad90e510d068"
    end
  end
  
  depends_on "docker"

  def install
    bin.install "docker-brennen"
  end

  test do
    assert_match "/usr/local/bin/docker-brennen", shell_output("which docker-brennen")
  end
end
