# This file was generated by GoReleaser. DO NOT EDIT.
class DockerBrennen < Formula
  desc "Cleanup unused Docker resources."
  homepage "https://github.com/splo/docker-brennen/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/splo/docker-brennen/releases/download/v0.1.0/docker-brennen_0.1.0_darwin_amd64.tar.gz"
    sha256 "40744c37ee1cbffebeb72c27f7904db495594cbcbfe4473c0a119b386f7a3f3d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/splo/docker-brennen/releases/download/v0.1.0/docker-brennen_0.1.0_linux_amd64.tar.gz"
      sha256 "8b2b666f9f6a816ab01526f4d5c4ce7f92cf7a12ddd4a2ce1b62ef844f8d9d2f"
    end
  end
  
  depends_on "docker"

  def install
    bin.install "docker-brennen"
  end

  test do
    assert_match "/usr/local/bin/docker-brennen", shell_output("which docker-brennen")
  end
end
