# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerBrennen < Formula
  desc "Cleanup unused Docker resources."
  homepage "https://github.com/splo/docker-brennen/"
  version "0.3.1"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/splo/docker-brennen/releases/download/v0.3.1/docker-brennen_0.3.1_darwin_arm64.tar.gz"
      sha256 "235b03b06bdae40aca83a45c1ffb0b3909f681eed4febd977f119f7de3d8f948"

      def install
        bin.install "docker-brennen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/splo/docker-brennen/releases/download/v0.3.1/docker-brennen_0.3.1_darwin_amd64.tar.gz"
      sha256 "04b09aafe9b4360607a2bf4a912598765efa055b52dea8a7bd58d77c5e7998d5"

      def install
        bin.install "docker-brennen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/splo/docker-brennen/releases/download/v0.3.1/docker-brennen_0.3.1_linux_arm64.tar.gz"
      sha256 "23f18a919bcd87842aa5ae071be63f6a7da713492f50821c089025984e5f805b"

      def install
        bin.install "docker-brennen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/splo/docker-brennen/releases/download/v0.3.1/docker-brennen_0.3.1_linux_amd64.tar.gz"
      sha256 "19ab997423710d6c0889cddcb5bfc292865e7a800afc3b01cccb6c4dc316c257"

      def install
        bin.install "docker-brennen"
      end
    end
  end

  test do
    assert_match(/docker-brennen$/, shell_output("which docker-brennen"), "Not correctly installed")
  end
end
