# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitDeleteMergedBranches < Formula
  desc "Delete branches present in local but deleted in remote"
  homepage "https://github.com/splo/git-delete-merged-branches"
  url "https://github.com/splo/git-delete-merged-branches/archive/refs/tags/v0.2.2.tar.gz"
  sha256 "efae6a38765ddba94463270b8f1945abf7a5374b1f38caa0b9957385d0add711"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    on_intel do
      url "https://github.com/splo/git-delete-merged-branches/releases/download/v0.2.2/git-delete-merged-branches-0.2.2-darwin-amd64.tar.gz"
      sha256 "2dd4216bab24d72ae3d8eeb05b7536385c238d49ae54277b31da2c85a3d5bd93"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/splo/git-delete-merged-branches/releases/download/v0.2.2/git-delete-merged-branches-0.2.2-linux-amd64.tar.gz"
      sha256 "15be2ee63e24757e4bf8ad94ac6841ac9f5bad93ff5931507928e9ed6996eeca"
    end
  end

  def install
    bin.install 'git-delete-merged-branches'
  end

  test do
    assert_match(/git-delete-merged-branches$/, shell_output("which git-delete-merged-branches"), "Not correctly installed")
  end
end
