# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitDeleteMergedBranches < Formula
  desc "Delete branches present in local but deleted in remote"
  homepage "https://github.com/splo/git-delete-merged-branches"
  url "https://github.com/splo/git-delete-merged-branches/archive/v0.2.1.tar.gz"
  sha256 "77b2b8b43878b581d5face30ee1fc4c9bbbe1bcb255f272a868b8f6bdcc986b6"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    on_intel do
      url "https://github.com/splo/git-delete-merged-branches/releases/download/v0.2.1/git-delete-merged-branches-0.2.1-darwin-amd64.tar.gz"
      sha256 "0cd46710e1e2dd9e532651c7ae8af64a3e3caf4733240f7694b59c8d2b9dcc9e"
    end

    on_arm do
      url "https://github.com/splo/git-delete-merged-branches/releases/download/v0.2.1/git-delete-merged-branches-0.2.1-darwin-arm64.tar.gz"
      sha256 "93f02494044b676575d145b0ddeb2635dcd7107f6ebc2855802e3467144ddfc3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/splo/git-delete-merged-branches/releases/download/v0.2.1/git-delete-merged-branches-0.2.1-linux-amd64.tar.gz"
      sha256 "111a4079efa32c67ec444a6d9d417e38ee0279419de2d3698e5ff92b61d7a2c8"
    end
  end

  def install
    bin.install 'git-delete-merged-branches'
  end

  test do
    assert_match(/git-delete-merged-branches$/, shell_output("which git-delete-merged-branches"), "Not correctly installed")
  end
end
